// src/views/BestDealsView.tsx
import React from "react";
import BestDeals from "../components/BestDeals";
import "../styles/BestDeals.css";

const BestDealsView: React.FC = () => {
  return (
    <>
      <div id="container2">
        <div className="head">
          <div className="head-thumb">
            <h2>Thumbnail</h2>
          </div>
          <div className="head-title">
            <h2>Title</h2>
          </div>
          <div className="head-price">
            <h2>Price</h2>
          </div>
          <div className="head-stores">
            <h2>Store</h2>
          </div>
        </div>
      </div>
      <BestDeals />
    </>
  );
};

export default BestDealsView;

// src/views/BestDealsView.vue
<template>
  <main class="content">
    <div id="container2">
      <div class="head">
        <div class="head-thumb">
          <h2>Thumbnail</h2>
        </div>
        <div class="haed-title">
          <h2>Title</h2>
        </div>
        <div class="head-price">
          <h2>Price</h2>
        </div>
        <div class="head-store">
          <h2>Store</h2>
        </div>
      </div>
    </div>
    <div id="app"></div>
  </main>
</template>

<script></script>
