// src/components/BestDeals.vue
<script setup>
import { ref } from "vue";
import axios from "axios";

const props = defineProps({
  maxPrice: {
    type: Number,
    default: 15,
  },
});

const deals = ref([]);

function getDeals() {
  axios
    .get("https://www.cheapshark.com/api/1.0/stores")
    .then((response) => {
      sessionStorage.setItem("stores", JSON.stringify(response.data));
      const stores = response.data;
      axios
        .get(
          `https://www.cheapshark.com/api/1.0/deals?upperPrice=${props.maxPrice}&sortBy=DealRating`
        )
        .then((response) => {
          const getDeals = response.data;

          getDeals.forEach((deal) => {
            const foundStore = stores.find(
              (store) => store.storeID === deal.storeID
            );
            deal.store = foundStore.storeName;
            deals.value.push(deal);
          });
        })
        .catch((error) => {
          console.log(error);
        });
    })
    .catch((error) => {
      console.log(error);
    });
}
getDeals();
</script>

<template>
  <div class="games">
    <div class="game" v-for="deal in deals" :key="deal.dealID">
      <div class="game-thumb">
        <img id="game-img" :src="deal.thumb" alt="Image missing" />
      </div>
      <div class="game-title">
        <p id="game-gametitle">{{ deal.title }}</p>
      </div>
      <div class="game-price">
        <p id="game-normalPrice">{{ deal.normalPrice }}</p>
        <p id="game-salesPrice">{{ deal.salePrice }}</p>
        <p id="game-savings">{{ deal.savings }}</p>
      </div>
      <div class="game-stores">
        <p id="game-store">{{ deal.store }}</p>
      </div>
    </div>
  </div>
</template>

// src/components/BestDeals.tsx
import React, { useEffect, useState } from "react";
import axios from "axios";
import "../styles/BestDeals.css";

interface ApiDeal {
  dealID: string;
  storeID: string;
  title: string;
  salePrice: string;
  normalPrice: string;
  savings: string;
  thumb: string;
}

interface Store {
  storeID: string;
  storeName: string;
}

interface DealWithStore extends ApiDeal {
  store: string;
}

interface BestDealsProps {
  maxPrice?: number;
}

const BestDeals: React.FC<BestDealsProps> = ({ maxPrice = 15 }) => {
  const [deals, setDeals] = useState<DealWithStore[]>([]);

  useEffect(() => {
    async function getDeals() {
      try {
        const storesRes = await axios.get<Store[]>(
          "https://www.cheapshark.com/api/1.0/stores"
        );
        sessionStorage.setItem("stores", JSON.stringify(storesRes.data));
        const stores = storesRes.data;

        const dealsRes = await axios.get<ApiDeal[]>(
          `https://www.cheapshark.com/api/1.0/deals?upperPrice=${maxPrice}&sortBy=DealRating`
        );

        const dealsWithStore: DealWithStore[] = dealsRes.data.map((deal) => {
          const foundStore = stores.find(
            (store) => store.storeID === deal.storeID
          );
          return {
            ...deal,
            store: foundStore ? foundStore.storeName : "Unknown",
          };
        });

        setDeals(dealsWithStore);
      } catch (error) {
        console.log(error);
      }
    }
    getDeals();
  }, [maxPrice]);

  return (
    <div className="games">
      {deals.map((deal: DealWithStore) => (
        <div className="game" key={deal.dealID}>
          <div className="game-thumb">
            <img id="game-img" src={deal.thumb} alt="Image missing" />
          </div>
          <div className="game-title">
            <p id="game-gametitle">{deal.title}</p>
          </div>
          <div className="game-price">
            <p id="game-normalPrice">${deal.normalPrice}</p>
            <p id="game-salesPrice">${deal.salePrice}</p>
            <p id="game-savings">{Math.round(parseFloat(deal.savings))}%</p>
          </div>
          <div className="game-stores">
            <p id="game-store">{deal.store}</p>
          </div>
        </div>
      ))}
    </div>
  );
};

export default BestDeals;
